"""
Flask Middleware for handling events and streams in a Flask SPA application.

This middleware intercepts incoming requests and outgoing responses to manage events and streams that can be used to trigger specific actions or display
messages to the user in a Flask SPA application.

It allows you to set CORS headers, manage events, and handle file streams for downloads.

Author: OpenAI's ChatGPT
Date: 2024-06
"""

import json
import zipfile
from dataclasses import asdict
from io import BytesIO
from typing import Any, List, Tuple

from flask import Flask, Request, Response, request, send_file

from .event_factory import EventFactory
from .types import Event, EventType, Stream


class FlaskMiddleware:
    def __init__(self, app: Flask, allow_origin="*", allow_methods="GET,POST,PUT,DELETE") -> None:
        self._app = app  # Store the Flask application instance for later use in request and response processing.
        self._allow_origin = allow_origin  # Set the allowed origin for CORS headers to enable cross-origin requests from the specified origin.
        self._allow_methods = allow_methods  # Set the allowed methods for CORS headers to enable cross-origin requests with the specified methods.

        self._wsgi_app = app.wsgi_app  # Store the original WSGI application to call it later in the __call__ method after modifying the response headers.

        self._request: Request
        self._response: Response
        self._events: List[Event] = []
        self._streams: List[Stream] = []

        # Override the WSGI application with this middleware to intercept requests and responses
        app.wsgi_app = self

        # Set up before_request and after_request handlers to manage request and response processing
        @app.before_request
        def _():
            """Before processing the request, this function is called to store the incoming request object for later use in the response processing.\n
            It allows the middleware to access the request data and context when modifying the response headers or managing events and streams.
            """

            self._request = request

        @app.after_request
        def _(response: Response):
            """After processing the request, this function is called to modify the response headers and manage events and streams.\n
            It adds CORS headers, event headers, and handles file streams for downloads before returning the final response to the client.

            Args:
                response (Response): The response object generated by the Flask application after processing the request.

            """
            if self._streams:
                if len(self._streams) == 1:  # Single file
                    stream = self._streams[0]
                    response = send_file(stream.data, download_name=stream.filename, mimetype=stream.mimetype)
                else:  # Multiple files => ZIP them !
                    zip_buffer = BytesIO()
                    zip_filename = "+".join([s.filename for s in self._streams]) + ".zip"

                    # Create an in-memory ZIP archive
                    with zipfile.ZipFile(zip_buffer, "w") as zipf:
                        for stream in self._streams:
                            stream.data.name = stream.filename
                            zipf.writestr(stream.filename, stream.data.getvalue())
                    # Rewind buffer
                    zip_buffer.seek(0)

                    # Remove the DOWNLOAD events and replacehem by a new one !
                    for event in list(filter(lambda x: x.type == EventType.DOWNLOAD, self._events)):
                        self._events.remove(event)

                    # Create a new event for this fresh zip file !
                    event = EventFactory.download(zip_buffer, "application/zip", zip_filename, "download")

                    # Clear the current streams
                    self._streams.clear()

                    # Add the new event
                    self.add_event(event)

                    response = send_file(zip_buffer, download_name=zip_filename, mimetype="application/zip")

            return response

    def __call__(self, environ, start_response):
        def custom_start_response(status: str, headers: List[Tuple[str, Any]], exc_info=None):
            """Custom start_response function to modify the response headers before sending the response back to the client.\n
            It adds CORS headers, event headers, and handles file streams for downloads before calling the original start_response function to continue
            processing the response.

            Args:
                status (str): The HTTP status code and message for the response (e.g., "200 OK").

                headers (List[Tuple[str, Any]]): A list of tuples representing the HTTP headers to be included in the response. Each tuple contains the header name and its corresponding value.

                exc_info: Optional exception information for error handling (default is None).

            Returns:
                The result of calling the original start_response function with the modified headers to continue processing the response and send it back to the client.
            """

            # Add CORS headers to allow cross-origin requests from the specified origin and methods
            # to ensure that the SPA can interact with the backend API without issues.
            headers.append(("Access-Control-Allow-Origin", self._allow_origin))
            headers.append(("Access-Control-Allow-Methods", self._allow_methods))

            # If there are any events in the _events list, convert them to dictionaries and add them as a
            # JSON string in the "x-nd-event" header, then clear the _events list for the next request.
            # This allows the SPA to receive and process any events that were generated during the request
            # processing and ensures that the events are not duplicated in subsequent responses.
            if self._events:
                event_list = [asdict(e) for e in self._events]
                headers.append(("x-nd-event", json.dumps(event_list)))
                self._events.clear()

            # If there are any streams in the _streams list, clear the list to ensure that any file streams
            # that were generated during the request processing are not included in subsequent responses.
            if self._streams:
                self._streams.clear()

            # Call the original start_response function with the modified headers to continue processing the response.
            return start_response(status, headers, exc_info)

        # Call the original WSGI application with the custom start_response function to generate the response.
        return self._wsgi_app(environ, custom_start_response)

    def is_spa_request(self) -> bool:
        return isinstance(self._request.headers.get("X-Nd-Version"), str)

    def add_event(self, event: Event):
        """Add an event to the _events list, which will be included in the response headers for the SPA to process and trigger specific
        actions or display messages to the user.

        Args:
            event (Event): The event object to be added to the _events list.\n
                        It will be converted to a dictionary and included in the "x-nd-event" header for the SPA to process.
        """
        # If the event has a stream associated with it,
        # add the stream to the _streams list and remove it from the event before adding the event to the _events list.
        if event.stream:
            self._streams.append(event.stream)
            del event.stream
        self._events.append(event)
